package org.example.waterf.entity.enums;

public enum TelegramState {

    SHARING_CONTACT, ENTERING_CODE, SHARING_LOCATION, WAITING, CABINET, SELECTING_BOTTLE_TYPES, ENTERING_BOTTLES_AMOUNT, SELECTING_TIME, ACCEPT_ORDER, START

}
